# Aufgabe - 6

<div class="alert alert-block alert-danger">

### Student Nutzername 1: ---------

### Student Nutzername 2: ---------

</div>

Assume : you are the TEACHER of this lecture and you want to check, how good the students understood the last lecture. Formulate 5 questions and 5 expected answers by which you check how well the students did understand the lecture. 
In each cell below type one question and answer <br>
<b>(10 points )</b> 2 points for each question and answer

Qn1:

YOUR ANSWER HERE

Qn2:

YOUR ANSWER HERE

Qn3:

YOUR ANSWER HERE

Qn4:

YOUR ANSWER HERE

Qn5:

YOUR ANSWER HERE

In [ ]:
import pandas as pd
import random
import numpy as np
import scipy
from scipy import stats
import matplotlib.pyplot as plt
%matplotlib inline

## Question 1:

Reproduce the given scatter plot of sample means for different samples (printed from Fig. 6.1. p148 )using the heights dataset	.<br>
a) Sample elements with replacement to construct subsets of sizes 9,16,25,..,,81 (see figure) <br>
b) Compute the sample mean for each of 100 subsets, i.e there are 100 means for each sample size <br>
c) Represent these means by a boxplot <br>
d) Compute the population mean and the standard error as measured by the	population standard derivation. In	the	figure “x” to the side of each column is the population mean while the vertical bar are a 1-standard	error above	and	below the population mean.	 To plot a vertical bar the function bar of	matplotlib.pyplot can be used. <br>

Analyze how (i) the sample means vary less as the sample gets bigger and (ii) the sample means largely lie within the error bars, as they should.
<img src="./images/fig1.png" />

### Load the dataset

Load the bodyFat dataset as a pandas Dataframe in the below cell as "df"

Hint : use the HEIGHTS columns to draw samples

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

In [ ]:
def generate_sample_meanlist(sample_size,subset_size,df):
    """
    This function should get the dataframe,sample size and subset size and 
    return the mean of each sample as a list. (list must contain 100 means)
    """
    # YOUR CODE HERE
    raise NotImplementedError()
    return samples_meanlist

In [ ]:
subset_size = [9,16,25,36,49,64,81]
sample_size = 100

mean_dict = {i:[] for i in subset_size }

for size in subset_size:
    mean_dict[size] = generate_sample_meanlist(sample_size,size,df)
  

 
#WRITE TOUR PLOTTING CODE HERE
# YOUR CODE HERE
raise NotImplementedError()

Compute the population mean and the standard error . Add them to the plot as shown in the given plot

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

In the below cell, Analyze how (i) the sample means vary less as the sample gets bigger and (ii) the sample means largely lie within the error bars, as they should

YOUR ANSWER HERE

## Question 2:

<b>Investigating the construction of confidence intervals</b> The UC Irvine Machine Learning data repository hosts a dataset giving various measurements of abalone at https://archive.ics.uci.edu/ml/datasets/Abalone. This data comes from an original study by W.J. Nash, T.L. Sellers, S.R. Talbot, A.J. Cawthorn and W. B. Ford, called “The Population Biology of Abalone (Haliotis species) in Tasmania. I. Blacklip Abalone (H. rubra) from the North Coast and Islands of Bass Strait”, Sea Fisheries Division, Technical Report No. 48 (ISSN 1034-3288) (1994). The data was donated by S. Waugh. There are 4177 records.

We will use the Length measurement. We will assume that the 4177 records is the entire population. Compute the population mean.

(a) Draw 10,000 samples of 20 records at random with replacement. Use each sample to compute a centered 90% confidence interval for the population mean, using the t-distribution. For what fraction of samples does the true population mean lie inside the interval?

(b) Draw 10,000 samples of 10 records at random with replacement. Use each sample to compute a centered 90% confidence interval for the population mean, using the t-distribution. For what fraction of samples does the true population mean lie inside the interval?

(c) Draw 10,000 samples of 10 records at random with replacement. Use each sample to compute a centered 90% confidence interval for the population mean, using a normal model (which you really shouldn’t, because the sample is too small). For what fraction of samples does the true population mean lie inside the interval?

(d) Now repeat the last two subexercises, but using only three records. What conclusion do you draw?

#### Load the dataset "abalone.data.txt"

Hint: Use the Length column for generating samples

In [ ]:
df = pd.read_csv("./data/abalone.data.txt",header=None,names = ["Sex","Length","Diameter","Height","Whole weight",\
                                                           "Shucked weight","Viscera weight","Shell weight","Rings"])
df.head()

### Compute the population mean

In [ ]:
def population_mean(df):
    
    """
    This function should get the dataframe,and 
    return the population mean of the length column
    """
    # YOUR CODE HERE
    raise NotImplementedError()
    return pop_mean


## computing the population mean
pop_mean = population_mean(df)
print("Population Mean:",population_mean(df))

In [ ]:
# This cell is for grading purpose . Please ignore it.

In [ ]:
def generate_samples(sample_size,record_size,df): 
    np.random.seed(2)
    
    """
    This function should get the dataframe,sample size , record size and 
    return a list containting 10000 samples of record size
    
    e,g for sample_size = 5 and record_size = 2 
    [array([0.5 , 0.51]),
     array([0.47, 0.5 ]),
     array([0.425, 0.545]),
     array([0.43, 0.58]),
     array([0.47 , 0.585])]
    """
    # YOUR CODE HERE
    raise NotImplementedError()
    return samples
        
def T_compute_fraction_of_samples(samples,confidence,pop_mean):
    
    """
    USING T- DISTRIBUTION
    python: scipy.stats.t
    This function should get the samples,confidence, population mean and 
    return a fraction of samples does the true population mean lie inside the interval
    
    e.g it should return 0.50 for 50% inside the interval
    """
    # YOUR CODE HERE
    raise NotImplementedError()

def normal_compute_fraction_of_samples(samples,z_critical,pop_mean):
    
    """
    USING NORMAL - DISTRIBUTION
    
    
    python: scipy.stats.t
    This function should get the samples,z_critical, population mean and 
    return a fraction of samples does the true population mean lie inside the interval
    
    Note:
    z_critical for 90% confidence is 1.645
    z_critical for 95% confidence is 1.96
    z_critical for 85% confidence is 1.44
    
    e.g it should return 0.50 for 50% inside the interval
    """
    # YOUR CODE HERE
    raise NotImplementedError()


### Task 2 (a)

In [ ]:
sample_size = 10000
record_size = 20
samples = generate_samples(sample_size,record_size,df)
confidence = 0.90
print("Fraction of samples does the true population mean lie inside the interval(20 records):",\
      T_compute_fraction_of_samples(samples,confidence,pop_mean))

In [ ]:
# This cell is for grading purpose . Please ignore it.

### Task 2 (b)

In [ ]:
sample_size = 10000
record_size = 10
samples = generate_samples(sample_size,record_size,df)
confidence = 0.90
print("Fraction of samples does the true population mean lie inside the interval(10 records):",\
      T_compute_fraction_of_samples(samples,confidence,pop_mean))

In [ ]:
# This cell is for grading purpose . Please ignore it.

### Task 2 (c)

In [ ]:
sample_size = 10000
record_size = 10
samples = generate_samples(sample_size,record_size,df)

# For 90 percent confidence interval , the z critical value will be 1.645
z_critical = 1.645

print("Fraction of samples does the true population mean lie inside the interval(10 records) using normal model:",\
      normal_compute_fraction_of_samples(samples,z_critical,pop_mean))

In [ ]:
# This cell is for grading purpose . Please ignore it.

### Task 2 (d)

In [ ]:
# using t- distribution with three records
sample_size = 10000
record_size = 3
samples = generate_samples(sample_size,record_size,df)
confidence = 0.90
print("Fraction of samples does the true population mean lie inside the interval(3 records):",\
      T_compute_fraction_of_samples(samples,confidence,pop_mean))

# using normal modal with three records
sample_size = 10000
record_size = 3
samples = generate_samples(sample_size,record_size,df)

# For 90 percent confidence interval , the z critical value will be 1.645
z_critical = 1.645

print("Fraction of samples does the true population mean lie inside the interval(3 records) using normal model:",\
      normal_compute_fraction_of_samples(samples,z_critical,pop_mean))

In [ ]:
# This cell is for grading purpose . Please ignore it.

What conclusion do you draw?

write your conclusion in the below cell

YOUR ANSWER HERE

<div class="alert alert-block alert-success">
<h1>Confidence intervalls, H0</h1>
<h2>Topics:</h2>
<h3>testing hypothesis</h3>
<h3>using confidence intervall, length / position </h3>
</div>
<div class="alert alert-block alert-info">
<h4> python: scipy.stats.t , scipy.stats.norm OR statsmodels.stats.api</h4>
</div>

## Question 3:

A manufacturer of smartphones states on its website that at least 97% work flawlessly. After a reseller sold 280 smartphones, ten are returned due to defects. Investigate whether the reseller can still trust the manufacturer's claim if the significance level is 5%. Formulate a decision rule (i.e., an integer K for the critical region).

YOUR ANSWER HERE

## Question 4:

A manufacturer lets the failure probability of a technical device under increased load examine. To determine a confidence interval for the unknown probability, a series of experiments is performed.
Let $\pi$ be the probability of failure in a trial.

The result of the test series is the sample $(X_1, ..., X_n)$ where

$X_i = 1$, if a failure occurs on the i-th attempt, or $= 0$ if there is no failure on the i-th attempt.

Then $(X_1, ..., X_n)$ is sampled from $X \sim B(1, \pi)$

We are looking for a confidence interval for $\pi$ at level $1 - \alpha = 0.90$. The results of the following series of experiments are considered:

a. with $n = 60$ attempts a total of 12 failures occurred. First calculate the point estimate for $\pi_{60}$, then the confidence interval according to the formula from the lecture.

b. the established confidence interval is too wide for the manufacturer;
He therefore orders another 30 attempts with shows 7 more failures. What does the confidence interval look like now?

Write your answer for 4(a) in the below cell

YOUR ANSWER HERE

Write your answer for 4(b) in the below cell

YOUR ANSWER HERE

## Question 5:

Two urns that are not distinguishable externally are known to contain white and black balls, in urn 1 30% are white balls and 50% are white balls in urn 2.

An urn is chosen randomly, then drawn 50 times. H0 (null hypothesis) is: urn 1 has been chosen.

a. which draw results (counts) lead to a rejection of H0 at a 10% level of significance?

b. what is the probability that (at a significance level of 10%) the hypothesis "we draw from urn 1" was ***not rejected***, although -in reality- the draw was done from urn 2?

c. we define the critical region to start at $K=21$ (i.e. $K=[21,22,...)$) s.t. we reject the thesis "it is urn 1" if more than 20 white balls are drawn. How big is the error of 1st kind in this case?

d. Now: after choosing 50 times, you get 20 times a white ball. For the correct indication of the urn used for the lottery you are awarded a price. On which urn would you bet?

Write your answer for 5(a) in the below cell

YOUR ANSWER HERE

Write your answer for 5(b) in the below cell

YOUR ANSWER HERE

Write your answer for 5(c) in the below cell

YOUR ANSWER HERE

Write your answer for 5(d) in the below cell

YOUR ANSWER HERE

# <center>Merry Christmas !! </center>